name: sync commands

on:
  push:
    branches: [ main ]
    paths: 
      - 'commands/**'
  workflow_dispatch:

jobs:
  sync_commands:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Run sync script
        run: node scripts/updateCommands.js
        env:
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
