name: update tradeable items

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  update_tradeable_items:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        
      - name: Run update script
        run: npm run scrapeExchangeItems
        
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/tradeable_items.json
          git commit -m "`date` update"
          git push
